# Generated by Django 4.0 on 2021-12-28 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[(1, 'Lightweight'), (2, 'Middleweight'), (3, 'Cruiserweight'), (4, 'Heavyweight')], max_length=50)),
                ('weightLimit', models.IntegerField()),
                ('batteryCapacity', models.IntegerField()),
                ('state', models.CharField(choices=[(1, 'IDLE'), (2, 'LOADING'), (3, 'LOADED'), (4, 'DELIVERING'), (5, 'DELIVERED'), (6, 'RETURNING')], max_length=50)),
                ('loaded', models.BooleanField(default=False)),
                ('loadedMedication', models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Drones.medication')),
            ],
        ),
    ]
